language: ruby
sudo: false

rvm:
  - "2.0"
  - "2.1"
  - "2.2"

env:
  - ACTIVE_RECORD_VERSION="~> 4.2.0"
  - ACTIVE_RECORD_VERSION="~> 4.1.0"
  - ACTIVE_RECORD_VERSION="~> 4.0.0"
  - ACTIVE_RECORD_VERSION="~> 3.2.0"
