name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build And Test
        run: |
          docker-compose up -d db
          docker-compose up test
